services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      # HTTP port
      - "80:80"
      # web UI (enabled by --api.insecure=true)
      - "5000:8000"
    volumes:
      # so traefik can listen to docker events
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_ENV=development
      - DATABASE_URI=postgresql://hello_fastapi:hello_fastapi@db/hello_fastapi_dev
    command: >
      sh -c "
        /app/.venv/bin/alembic upgrade head &&
        /app/.venv/bin/uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
      "
    develop:
      watch:
        - action: sync
          path: ./
          target: /app/
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
    depends_on:
      - db

  db:
    image: postgres:17.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
      - POSTGRES_DB=hello_fastapi_dev

volumes:
  postgres_data:
